import {
  SkillItem,
  AssessmentItem,
  LearningRoadmapData,
  JobPostingItem,
  CandidateItem,
  MentorshipSessionItem,
  InstitutionAnalytics,
} from "@/types";

export const MOCK_SKILLS: SkillItem[] = [
  {
    id: "skill-1",
    name: "React.js & Next.js",
    category: "Technical",
    description: "Modern component architecture, SSR, hooks, and App Router",
    proficiencyLevel: 4,
    verificationStatus: "ASSESSMENT_VERIFIED",
    score: 92,
    lastAssessedAt: "2026-08-15",
  },
  {
    id: "skill-2",
    name: "Python & Fast-API",
    category: "Technical",
    description: "Async web development, data pipelines, API contracts",
    proficiencyLevel: 4,
    verificationStatus: "ASSESSMENT_VERIFIED",
    score: 88,
    lastAssessedAt: "2026-08-10",
  },
  {
    id: "skill-3",
    name: "PostgreSQL & Prisma",
    category: "Technical",
    description: "Relational database modeling, indexing, ACID transactions",
    proficiencyLevel: 3,
    verificationStatus: "FACULTY_ENDORSED",
    score: 78,
    lastAssessedAt: "2026-07-28",
  },
  {
    id: "skill-4",
    name: "Docker & Containerization",
    category: "Tool",
    description: "Multi-stage builds, compose orchestration, microservices",
    proficiencyLevel: 2,
    verificationStatus: "SELF_REPORTED",
    score: 60,
  },
  {
    id: "skill-5",
    name: "Machine Learning (PyTorch)",
    category: "Domain",
    description: "Deep learning, vector embeddings, fine-tuning LLMs",
    proficiencyLevel: 3,
    verificationStatus: "ASSESSMENT_VERIFIED",
    score: 84,
    lastAssessedAt: "2026-08-20",
  },
  {
    id: "skill-6",
    name: "System Design & Architecture",
    category: "Technical",
    description: "High availability, load balancing, caching strategies",
    proficiencyLevel: 3,
    verificationStatus: "SELF_REPORTED",
    score: 65,
  },
];

export const MOCK_ASSESSMENTS: AssessmentItem[] = [
  {
    id: "assess-1",
    skillName: "React.js & Next.js",
    title: "Advanced Next.js App Router & Performance Mastery",
    durationMins: 25,
    difficultyLevel: "Advanced",
    passingScore: 75,
    totalQuestions: 15,
    isCompleted: true,
    score: 92,
  },
  {
    id: "assess-2",
    skillName: "Docker & Containerization",
    title: "Docker Fundamentals & Production Deployment",
    durationMins: 20,
    difficultyLevel: "Intermediate",
    passingScore: 70,
    totalQuestions: 12,
    isCompleted: false,
  },
  {
    id: "assess-3",
    skillName: "Machine Learning (PyTorch)",
    title: "Deep Learning Architectures & Model Evaluation",
    durationMins: 30,
    difficultyLevel: "Advanced",
    passingScore: 80,
    totalQuestions: 20,
    isCompleted: true,
    score: 84,
  },
  {
    id: "assess-4",
    skillName: "Cloud Computing (AWS/GCP)",
    title: "Cloud Infrastructure, IAM & Serverless Architecture",
    durationMins: 25,
    difficultyLevel: "Intermediate",
    passingScore: 70,
    totalQuestions: 15,
    isCompleted: false,
  },
];

export const MOCK_ROADMAP: LearningRoadmapData = {
  id: "roadmap-1",
  targetRole: "Full-Stack AI Solutions Architect",
  gapSummary:
    "You have strong React and Python skills (88%+), but need to upgrade Containerization (Docker/K8s) and Cloud Infrastructure to reach 95%+ industry match.",
  estimatedHours: 36,
  progressPercent: 65,
  steps: [
    {
      id: "node-1",
      stepNumber: 1,
      title: "Master Multi-Stage Docker Builds & Mini-Services",
      description: "Learn how to optimize production container images under 150MB with Alpine Linux.",
      resourceType: "VIDEO",
      resourceUrl: "https://youtube.com",
      isCompleted: true,
    },
    {
      id: "node-2",
      stepNumber: 2,
      title: "Vector Embeddings & Semantic Search in Postgres (pgvector)",
      description: "Implement cosine similarity queries for recommendation engines.",
      resourceType: "PROJECT",
      resourceUrl: "https://github.com",
      isCompleted: true,
    },
    {
      id: "node-3",
      stepNumber: 3,
      title: "CI/CD Pipeline with GitHub Actions & Automated Testing",
      description: "Build an automated linting, test, and container deployment workflow.",
      resourceType: "ARTICLE",
      resourceUrl: "https://docs.github.com",
      isCompleted: false,
    },
    {
      id: "node-4",
      stepNumber: 4,
      title: "CapStone Project: Scalable AI Microservice & Recruiter ATS",
      description: "Deploy an end-to-end multi-tenant application with rate limiting and Redis caching.",
      resourceType: "CERT",
      resourceUrl: "https://coursera.org",
      isCompleted: false,
    },
  ],
};

export const MOCK_JOBS: JobPostingItem[] = [
  {
    id: "job-1",
    companyName: "Microsoft India",
    companyLogo: "https://images.unsplash.com/photo-1642543492481-44e81e3914a7?w=100&auto=format&fit=crop&q=80",
    title: "Graduate Software Engineer Intern - Cloud & AI",
    type: "INTERNSHIP",
    location: "Bengaluru / Hybrid",
    stipendSalary: "₹1,25,000/mo",
    deadline: "2026-09-30",
    status: "OPEN",
    minCgpa: 8.0,
    matchScore: 94,
    description:
      "Join the Azure Cloud platform team building next-generation AI infrastructure, distributed microservices, and customer-facing APIs.",
    requiredSkills: [
      { name: "React.js & Next.js", weight: 4, isMandatory: true },
      { name: "Python & Fast-API", weight: 5, isMandatory: true },
      { name: "PostgreSQL & Prisma", weight: 4, isMandatory: true },
      { name: "Docker", weight: 3, isMandatory: false },
    ],
    applicationStatus: "SHORTLISTED",
  },
  {
    id: "job-2",
    companyName: "Razorpay",
    companyLogo: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=100&auto=format&fit=crop&q=80",
    title: "Full-Stack Developer (Payments Platform)",
    type: "FULL_TIME",
    location: "Bengaluru / Remote",
    stipendSalary: "₹24,00,000/yr",
    deadline: "2026-10-15",
    status: "OPEN",
    minCgpa: 7.5,
    matchScore: 88,
    description:
      "Work on mission-critical payment gateway systems handling millions of daily transactions with ultra-low latency.",
    requiredSkills: [
      { name: "TypeScript", weight: 5, isMandatory: true },
      { name: "Next.js", weight: 4, isMandatory: true },
      { name: "PostgreSQL", weight: 4, isMandatory: true },
      { name: "System Design", weight: 4, isMandatory: true },
    ],
    applicationStatus: "APPLIED",
  },
  {
    id: "job-3",
    companyName: "Tata Elxsi",
    companyLogo: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=100&auto=format&fit=crop&q=80",
    title: "AI/ML Systems Intern",
    type: "INTERNSHIP",
    location: "Pune / On-Site",
    stipendSalary: "₹45,000/mo",
    deadline: "2026-09-20",
    status: "OPEN",
    minCgpa: 7.0,
    matchScore: 82,
    description:
      "Design computer vision and edge AI models for automotive and smart industrial diagnostics.",
    requiredSkills: [
      { name: "Python", weight: 5, isMandatory: true },
      { name: "PyTorch", weight: 5, isMandatory: true },
      { name: "Docker", weight: 3, isMandatory: true },
    ],
  },
];

export const MOCK_CANDIDATES: CandidateItem[] = [
  {
    id: "cand-1",
    studentId: "user-student-1",
    name: "Aarav Sharma",
    email: "aarav.sharma@institution.edu.in",
    department: "Computer Science & Engineering",
    cgpa: 8.8,
    readinessScore: 92,
    matchScore: 95,
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    skills: [
      { name: "React.js", level: 5, verified: true },
      { name: "Python", level: 4, verified: true },
      { name: "PostgreSQL", level: 4, verified: true },
      { name: "Docker", level: 3, verified: false },
    ],
    status: "SHORTLISTED",
    appliedAt: "2026-08-22",
  },
  {
    id: "cand-2",
    studentId: "user-student-2",
    name: "Sneha Reddy",
    email: "sneha.reddy@institution.edu.in",
    department: "Information Technology",
    cgpa: 9.1,
    readinessScore: 89,
    matchScore: 88,
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    skills: [
      { name: "Python", level: 5, verified: true },
      { name: "PyTorch", level: 5, verified: true },
      { name: "FastAPI", level: 4, verified: true },
    ],
    status: "UNDER_REVIEW",
    appliedAt: "2026-08-23",
  },
  {
    id: "cand-3",
    studentId: "user-student-3",
    name: "Rohan Varma",
    email: "rohan.varma@institution.edu.in",
    department: "Computer Science & Engineering",
    cgpa: 8.2,
    readinessScore: 76,
    matchScore: 79,
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    skills: [
      { name: "JavaScript", level: 4, verified: true },
      { name: "Node.js", level: 3, verified: false },
      { name: "MongoDB", level: 3, verified: true },
    ],
    status: "APPLIED",
    appliedAt: "2026-08-25",
  },
];

export const MOCK_MENTORSHIPS: MentorshipSessionItem[] = [
  {
    id: "mentor-1",
    facultyName: "Dr. Ramesh Verma",
    studentName: "Aarav Sharma",
    topic: "Capstone Architecture Review: Scalable Vector DB Systems",
    scheduledAt: "2026-08-30T14:30:00Z",
    meetingLink: "https://meet.google.com/abc-defg-hij",
    status: "CONFIRMED",
    notes: "Review schema diagram and verify indexing strategies for pgvector.",
  },
  {
    id: "mentor-2",
    facultyName: "Dr. Ramesh Verma",
    studentName: "Sneha Reddy",
    topic: "Industry Gap Preparation: Research Internship at Tata Elxsi",
    scheduledAt: "2026-09-02T11:00:00Z",
    meetingLink: "https://meet.google.com/xyz-uvwx-rst",
    status: "CONFIRMED",
    notes: "Discussion on computer vision edge model benchmarks.",
  },
];

export const MOCK_ANALYTICS: InstitutionAnalytics = {
  totalStudents: 1240,
  placementReadyPercentage: 78.5,
  averageSkillScore: 82.4,
  activeRecruiters: 46,
  totalOffers: 382,
  departmentReadiness: [
    { department: "Computer Science", total: 320, ready: 285, avgScore: 86.2 },
    { department: "Information Tech", total: 240, ready: 195, avgScore: 81.8 },
    { department: "Electronics & Comm", total: 280, ready: 180, avgScore: 75.4 },
    { department: "Electrical Engg", total: 210, ready: 135, avgScore: 71.0 },
    { department: "Mechanical Engg", total: 190, ready: 110, avgScore: 68.2 },
  ],
  skillDemandVsSupply: [
    { skill: "Cloud & DevOps", industryDemand: 95, studentSupply: 54 },
    { skill: "Full-Stack Next.js", industryDemand: 90, studentSupply: 78 },
    { skill: "AI / LLM Engineering", industryDemand: 88, studentSupply: 62 },
    { skill: "System Design", industryDemand: 85, studentSupply: 48 },
    { skill: "Cybersecurity", industryDemand: 80, studentSupply: 39 },
  ],
  placementFunnel: [
    { stage: "Registered Students", count: 1240 },
    { stage: "Skill-Assessed", count: 1080 },
    { stage: "Placement Ready (>75%)", count: 974 },
    { stage: "Shortlisted for Drives", count: 640 },
    { stage: "Offers Generated", count: 382 },
  ],
};
