"use client";

import React from "react";
import { Card } from "@/components/ui/Card";
import { Badge } from "@/components/ui/Badge";
import { Progress } from "@/components/ui/Progress";
import { Sparkles, AlertCircle, CheckCircle2, TrendingUp } from "lucide-react";

export const CurriculumAdvisory: React.FC = () => {
  const recommendations = [
    {
      course: "CS402: Cloud Architecture & DevOps",
      gap: "Current syllabus lacks hands-on Docker/Kubernetes container orchestration & CI/CD.",
      industryDemandGrowth: "+64% YoY",
      status: "ACTION_REQUIRED",
      urgency: "High",
    },
    {
      course: "CS305: Database Management Systems",
      gap: "Need to introduce Vector Databases (pgvector/Pinecone) & unstructured retrieval.",
      industryDemandGrowth: "+82% YoY",
      status: "IN_REVIEW",
      urgency: "Medium",
    },
    {
      course: "CS410: Modern Full-Stack Systems",
      gap: "Transition from legacy JSP/Servlets to Next.js App Router and TypeScript contracts.",
      industryDemandGrowth: "+45% YoY",
      status: "ADOPTED",
      urgency: "Low",
    },
  ];

  return (
    <Card className="h-full">
      <div className="flex items-center justify-between mb-4">
        <div>
          <div className="flex items-center gap-2">
            <h3 className="text-base font-bold text-white">Industry-Aligned Curriculum Advisory</h3>
            <Badge variant="purple" size="sm">
              <Sparkles size={11} /> AI Feedback Loop
            </Badge>
          </div>
          <p className="text-xs text-slate-400 mt-0.5">
            Automated recommendations generated by aggregating recruiter JD demands vs institutional syllabi.
          </p>
        </div>
      </div>

      <div className="space-y-3">
        {recommendations.map((rec, i) => (
          <div
            key={i}
            className="p-4 rounded-xl glass-card border border-white/5 hover:border-white/15 transition-all"
          >
            <div className="flex items-start justify-between gap-3">
              <div>
                <h4 className="text-sm font-bold text-white">{rec.course}</h4>
                <p className="text-xs text-slate-300 mt-1 leading-relaxed">{rec.gap}</p>
              </div>
              <Badge
                variant={
                  rec.urgency === "High"
                    ? "danger"
                    : rec.urgency === "Medium"
                    ? "warning"
                    : "success"
                }
                size="sm"
              >
                {rec.urgency} Priority
              </Badge>
            </div>

            <div className="flex items-center justify-between mt-3 pt-2.5 border-t border-white/5 text-xs">
              <span className="flex items-center gap-1 text-emerald-400 font-semibold">
                <TrendingUp size={13} /> Recruiter Hiring Surge: {rec.industryDemandGrowth}
              </span>
              <span className="text-slate-400 font-medium">NEP 2020 OBE Compliant</span>
            </div>
          </div>
        ))}
      </div>
    </Card>
  );
};
